// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: lobbies.proto
// </auto-generated>
// Original file comments:
// lobbies.proto
#pragma warning disable 0414, 1591, 8981, 0612
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Game.Lobbies {
  public static partial class LobbiesService
  {
    static readonly string __ServiceName = "game.lobbies.LobbiesService";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Game.Lobbies.CreateLobbyRequest> __Marshaller_game_lobbies_CreateLobbyRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Game.Lobbies.CreateLobbyRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Game.Lobbies.CreateLobbyResponse> __Marshaller_game_lobbies_CreateLobbyResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Game.Lobbies.CreateLobbyResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Game.Lobbies.JoinLobbyRequest> __Marshaller_game_lobbies_JoinLobbyRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Game.Lobbies.JoinLobbyRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Game.Lobbies.JoinLobbyResponse> __Marshaller_game_lobbies_JoinLobbyResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Game.Lobbies.JoinLobbyResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Game.Lobbies.LeaveLobbyRequest> __Marshaller_game_lobbies_LeaveLobbyRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Game.Lobbies.LeaveLobbyRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Game.Lobbies.LeaveLobbyResponse> __Marshaller_game_lobbies_LeaveLobbyResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Game.Lobbies.LeaveLobbyResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Google.Protobuf.WellKnownTypes.Empty> __Marshaller_google_protobuf_Empty = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Google.Protobuf.WellKnownTypes.Empty.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Game.Lobbies.GetLobbyListResponse> __Marshaller_game_lobbies_GetLobbyListResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Game.Lobbies.GetLobbyListResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Game.Lobbies.SubscribeLobbyRequest> __Marshaller_game_lobbies_SubscribeLobbyRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Game.Lobbies.SubscribeLobbyRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Game.Lobbies.LobbyEvent> __Marshaller_game_lobbies_LobbyEvent = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Game.Lobbies.LobbyEvent.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Game.Lobbies.SetLobbyCustomPropertiesRequest> __Marshaller_game_lobbies_SetLobbyCustomPropertiesRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Game.Lobbies.SetLobbyCustomPropertiesRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Game.Lobbies.SetLobbyCustomPropertiesResponse> __Marshaller_game_lobbies_SetLobbyCustomPropertiesResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Game.Lobbies.SetLobbyCustomPropertiesResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Game.Lobbies.SetUserInLobbyCustomPropertiesRequest> __Marshaller_game_lobbies_SetUserInLobbyCustomPropertiesRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Game.Lobbies.SetUserInLobbyCustomPropertiesRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Game.Lobbies.SetUserInLobbyCustomPropertiesResponse> __Marshaller_game_lobbies_SetUserInLobbyCustomPropertiesResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Game.Lobbies.SetUserInLobbyCustomPropertiesResponse.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Game.Lobbies.CreateLobbyRequest, global::Game.Lobbies.CreateLobbyResponse> __Method_CreateLobby = new grpc::Method<global::Game.Lobbies.CreateLobbyRequest, global::Game.Lobbies.CreateLobbyResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "CreateLobby",
        __Marshaller_game_lobbies_CreateLobbyRequest,
        __Marshaller_game_lobbies_CreateLobbyResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Game.Lobbies.JoinLobbyRequest, global::Game.Lobbies.JoinLobbyResponse> __Method_JoinLobby = new grpc::Method<global::Game.Lobbies.JoinLobbyRequest, global::Game.Lobbies.JoinLobbyResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "JoinLobby",
        __Marshaller_game_lobbies_JoinLobbyRequest,
        __Marshaller_game_lobbies_JoinLobbyResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Game.Lobbies.LeaveLobbyRequest, global::Game.Lobbies.LeaveLobbyResponse> __Method_LeaveLobby = new grpc::Method<global::Game.Lobbies.LeaveLobbyRequest, global::Game.Lobbies.LeaveLobbyResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "LeaveLobby",
        __Marshaller_game_lobbies_LeaveLobbyRequest,
        __Marshaller_game_lobbies_LeaveLobbyResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Game.Lobbies.GetLobbyListResponse> __Method_GetLobbyList = new grpc::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Game.Lobbies.GetLobbyListResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetLobbyList",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_game_lobbies_GetLobbyListResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Game.Lobbies.SubscribeLobbyRequest, global::Game.Lobbies.LobbyEvent> __Method_SubscribeLobby = new grpc::Method<global::Game.Lobbies.SubscribeLobbyRequest, global::Game.Lobbies.LobbyEvent>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "SubscribeLobby",
        __Marshaller_game_lobbies_SubscribeLobbyRequest,
        __Marshaller_game_lobbies_LobbyEvent);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Game.Lobbies.SetLobbyCustomPropertiesRequest, global::Game.Lobbies.SetLobbyCustomPropertiesResponse> __Method_SetLobbyCustomProperties = new grpc::Method<global::Game.Lobbies.SetLobbyCustomPropertiesRequest, global::Game.Lobbies.SetLobbyCustomPropertiesResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "SetLobbyCustomProperties",
        __Marshaller_game_lobbies_SetLobbyCustomPropertiesRequest,
        __Marshaller_game_lobbies_SetLobbyCustomPropertiesResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Game.Lobbies.SetUserInLobbyCustomPropertiesRequest, global::Game.Lobbies.SetUserInLobbyCustomPropertiesResponse> __Method_SetUserInCustomLobbyProperties = new grpc::Method<global::Game.Lobbies.SetUserInLobbyCustomPropertiesRequest, global::Game.Lobbies.SetUserInLobbyCustomPropertiesResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "SetUserInCustomLobbyProperties",
        __Marshaller_game_lobbies_SetUserInLobbyCustomPropertiesRequest,
        __Marshaller_game_lobbies_SetUserInLobbyCustomPropertiesResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Game.Lobbies.LobbiesReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of LobbiesService</summary>
    [grpc::BindServiceMethod(typeof(LobbiesService), "BindService")]
    public abstract partial class LobbiesServiceBase
    {
      /// <summary>
      /// 로비 생성
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Game.Lobbies.CreateLobbyResponse> CreateLobby(global::Game.Lobbies.CreateLobbyRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// 로비 참가
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Game.Lobbies.JoinLobbyResponse> JoinLobby(global::Game.Lobbies.JoinLobbyRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// 로비 나가기
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Game.Lobbies.LeaveLobbyResponse> LeaveLobby(global::Game.Lobbies.LeaveLobbyRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// 로비 목록 읽기
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Game.Lobbies.GetLobbyListResponse> GetLobbyList(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// 로비 구독 (Server-스트리밍. 클라이언트가 서버의 응답을 계속해서 읽을수있는 스트림이 필요하다)
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="responseStream">Used for sending responses back to the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>A task indicating completion of the handler.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task SubscribeLobby(global::Game.Lobbies.SubscribeLobbyRequest request, grpc::IServerStreamWriter<global::Game.Lobbies.LobbyEvent> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// 로비 프로퍼티 설정
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Game.Lobbies.SetLobbyCustomPropertiesResponse> SetLobbyCustomProperties(global::Game.Lobbies.SetLobbyCustomPropertiesRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// 유저 in 로비 프로퍼티 설정
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Game.Lobbies.SetUserInLobbyCustomPropertiesResponse> SetUserInCustomLobbyProperties(global::Game.Lobbies.SetUserInLobbyCustomPropertiesRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for LobbiesService</summary>
    public partial class LobbiesServiceClient : grpc::ClientBase<LobbiesServiceClient>
    {
      /// <summary>Creates a new client for LobbiesService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public LobbiesServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for LobbiesService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public LobbiesServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected LobbiesServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected LobbiesServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      /// <summary>
      /// 로비 생성
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Game.Lobbies.CreateLobbyResponse CreateLobby(global::Game.Lobbies.CreateLobbyRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CreateLobby(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// 로비 생성
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Game.Lobbies.CreateLobbyResponse CreateLobby(global::Game.Lobbies.CreateLobbyRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_CreateLobby, null, options, request);
      }
      /// <summary>
      /// 로비 생성
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Game.Lobbies.CreateLobbyResponse> CreateLobbyAsync(global::Game.Lobbies.CreateLobbyRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CreateLobbyAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// 로비 생성
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Game.Lobbies.CreateLobbyResponse> CreateLobbyAsync(global::Game.Lobbies.CreateLobbyRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_CreateLobby, null, options, request);
      }
      /// <summary>
      /// 로비 참가
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Game.Lobbies.JoinLobbyResponse JoinLobby(global::Game.Lobbies.JoinLobbyRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return JoinLobby(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// 로비 참가
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Game.Lobbies.JoinLobbyResponse JoinLobby(global::Game.Lobbies.JoinLobbyRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_JoinLobby, null, options, request);
      }
      /// <summary>
      /// 로비 참가
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Game.Lobbies.JoinLobbyResponse> JoinLobbyAsync(global::Game.Lobbies.JoinLobbyRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return JoinLobbyAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// 로비 참가
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Game.Lobbies.JoinLobbyResponse> JoinLobbyAsync(global::Game.Lobbies.JoinLobbyRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_JoinLobby, null, options, request);
      }
      /// <summary>
      /// 로비 나가기
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Game.Lobbies.LeaveLobbyResponse LeaveLobby(global::Game.Lobbies.LeaveLobbyRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return LeaveLobby(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// 로비 나가기
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Game.Lobbies.LeaveLobbyResponse LeaveLobby(global::Game.Lobbies.LeaveLobbyRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_LeaveLobby, null, options, request);
      }
      /// <summary>
      /// 로비 나가기
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Game.Lobbies.LeaveLobbyResponse> LeaveLobbyAsync(global::Game.Lobbies.LeaveLobbyRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return LeaveLobbyAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// 로비 나가기
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Game.Lobbies.LeaveLobbyResponse> LeaveLobbyAsync(global::Game.Lobbies.LeaveLobbyRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_LeaveLobby, null, options, request);
      }
      /// <summary>
      /// 로비 목록 읽기
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Game.Lobbies.GetLobbyListResponse GetLobbyList(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetLobbyList(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// 로비 목록 읽기
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Game.Lobbies.GetLobbyListResponse GetLobbyList(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetLobbyList, null, options, request);
      }
      /// <summary>
      /// 로비 목록 읽기
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Game.Lobbies.GetLobbyListResponse> GetLobbyListAsync(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetLobbyListAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// 로비 목록 읽기
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Game.Lobbies.GetLobbyListResponse> GetLobbyListAsync(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetLobbyList, null, options, request);
      }
      /// <summary>
      /// 로비 구독 (Server-스트리밍. 클라이언트가 서버의 응답을 계속해서 읽을수있는 스트림이 필요하다)
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncServerStreamingCall<global::Game.Lobbies.LobbyEvent> SubscribeLobby(global::Game.Lobbies.SubscribeLobbyRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SubscribeLobby(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// 로비 구독 (Server-스트리밍. 클라이언트가 서버의 응답을 계속해서 읽을수있는 스트림이 필요하다)
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncServerStreamingCall<global::Game.Lobbies.LobbyEvent> SubscribeLobby(global::Game.Lobbies.SubscribeLobbyRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncServerStreamingCall(__Method_SubscribeLobby, null, options, request);
      }
      /// <summary>
      /// 로비 프로퍼티 설정
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Game.Lobbies.SetLobbyCustomPropertiesResponse SetLobbyCustomProperties(global::Game.Lobbies.SetLobbyCustomPropertiesRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SetLobbyCustomProperties(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// 로비 프로퍼티 설정
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Game.Lobbies.SetLobbyCustomPropertiesResponse SetLobbyCustomProperties(global::Game.Lobbies.SetLobbyCustomPropertiesRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_SetLobbyCustomProperties, null, options, request);
      }
      /// <summary>
      /// 로비 프로퍼티 설정
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Game.Lobbies.SetLobbyCustomPropertiesResponse> SetLobbyCustomPropertiesAsync(global::Game.Lobbies.SetLobbyCustomPropertiesRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SetLobbyCustomPropertiesAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// 로비 프로퍼티 설정
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Game.Lobbies.SetLobbyCustomPropertiesResponse> SetLobbyCustomPropertiesAsync(global::Game.Lobbies.SetLobbyCustomPropertiesRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_SetLobbyCustomProperties, null, options, request);
      }
      /// <summary>
      /// 유저 in 로비 프로퍼티 설정
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Game.Lobbies.SetUserInLobbyCustomPropertiesResponse SetUserInCustomLobbyProperties(global::Game.Lobbies.SetUserInLobbyCustomPropertiesRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SetUserInCustomLobbyProperties(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// 유저 in 로비 프로퍼티 설정
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Game.Lobbies.SetUserInLobbyCustomPropertiesResponse SetUserInCustomLobbyProperties(global::Game.Lobbies.SetUserInLobbyCustomPropertiesRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_SetUserInCustomLobbyProperties, null, options, request);
      }
      /// <summary>
      /// 유저 in 로비 프로퍼티 설정
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Game.Lobbies.SetUserInLobbyCustomPropertiesResponse> SetUserInCustomLobbyPropertiesAsync(global::Game.Lobbies.SetUserInLobbyCustomPropertiesRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SetUserInCustomLobbyPropertiesAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// 유저 in 로비 프로퍼티 설정
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Game.Lobbies.SetUserInLobbyCustomPropertiesResponse> SetUserInCustomLobbyPropertiesAsync(global::Game.Lobbies.SetUserInLobbyCustomPropertiesRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_SetUserInCustomLobbyProperties, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected override LobbiesServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new LobbiesServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static grpc::ServerServiceDefinition BindService(LobbiesServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_CreateLobby, serviceImpl.CreateLobby)
          .AddMethod(__Method_JoinLobby, serviceImpl.JoinLobby)
          .AddMethod(__Method_LeaveLobby, serviceImpl.LeaveLobby)
          .AddMethod(__Method_GetLobbyList, serviceImpl.GetLobbyList)
          .AddMethod(__Method_SubscribeLobby, serviceImpl.SubscribeLobby)
          .AddMethod(__Method_SetLobbyCustomProperties, serviceImpl.SetLobbyCustomProperties)
          .AddMethod(__Method_SetUserInCustomLobbyProperties, serviceImpl.SetUserInCustomLobbyProperties).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static void BindService(grpc::ServiceBinderBase serviceBinder, LobbiesServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_CreateLobby, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Game.Lobbies.CreateLobbyRequest, global::Game.Lobbies.CreateLobbyResponse>(serviceImpl.CreateLobby));
      serviceBinder.AddMethod(__Method_JoinLobby, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Game.Lobbies.JoinLobbyRequest, global::Game.Lobbies.JoinLobbyResponse>(serviceImpl.JoinLobby));
      serviceBinder.AddMethod(__Method_LeaveLobby, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Game.Lobbies.LeaveLobbyRequest, global::Game.Lobbies.LeaveLobbyResponse>(serviceImpl.LeaveLobby));
      serviceBinder.AddMethod(__Method_GetLobbyList, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Google.Protobuf.WellKnownTypes.Empty, global::Game.Lobbies.GetLobbyListResponse>(serviceImpl.GetLobbyList));
      serviceBinder.AddMethod(__Method_SubscribeLobby, serviceImpl == null ? null : new grpc::ServerStreamingServerMethod<global::Game.Lobbies.SubscribeLobbyRequest, global::Game.Lobbies.LobbyEvent>(serviceImpl.SubscribeLobby));
      serviceBinder.AddMethod(__Method_SetLobbyCustomProperties, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Game.Lobbies.SetLobbyCustomPropertiesRequest, global::Game.Lobbies.SetLobbyCustomPropertiesResponse>(serviceImpl.SetLobbyCustomProperties));
      serviceBinder.AddMethod(__Method_SetUserInCustomLobbyProperties, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Game.Lobbies.SetUserInLobbyCustomPropertiesRequest, global::Game.Lobbies.SetUserInLobbyCustomPropertiesResponse>(serviceImpl.SetUserInCustomLobbyProperties));
    }

  }
}
#endregion
